<style>
    .card {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        margin: 10px;
        width: 300px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .card img {
        max-width: 100%;
        height: auto;
    }

    .card h3 {
        font-size: 18px;
        margin-top: 10px;
    }

    .card p {
        margin-top: 10px;
    }
</style>
<div style="display:flex;">
	<?php $url = Mage::getBaseUrl('media'); ?>
	<?php foreach ($this->getBrands() as $brand) : ?>
	<?php $path = $url . $brand->image; ?>
    <div class="card">
        <a href="<?php echo $this->getRewriteKey($brand); ?>"><img src="<?php echo $path; ?>" height = "400px" width = "300px" alt="Brand 1">
        </a>
        <h3 align="center"><?php echo $brand->name; ?></h3>
    </div>
	<?php endforeach; ?>
</div>
